import Head from "next/head";
import Image from "next/image";
import Main from "./components/Main";
// import Skills from "./components/Skills";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-14 text-black lg:space-y-24">
        <main className="max-w-4xl mx-auto antialiased">
          <Main />
          {/* <Skills /> */}
        </main>
      </div>
    </div>
  );
}
